### ISSUE TITLE
Error when filename contains parenthesis

### ISSUE THREAD

**Issue by romgrk** [kevva/xdg-trash#9]
{ [Error: Command failed: /bin/sh -c df -kP /home/romgrk/github/filrk/bar(2).txt
/bin/sh: 1: Syntax error: "(" unexpected
]
  killed: false,
  code: 2,
  signal: null,
  cmd: '/bin/sh -c df -kP /home/romgrk/github/filrk/bar(2).txt' }

**Comment by kevva** [comment]
Should be fixed in https://github.com/kevva/mount-point/commit/063c8757cebe4d658614107596d1271a650c53b5.
